### ISSUE TITLE
[stylelint-config] Mettre a jour stylelint-config-standard

### ISSUE THREAD

**Issue by GTony** [kronostechnologies/standards#128]
`function-calc-no-invalid` est deprecated depuis la version 13.7.0 de `stylelint` et retiré depuis la version 14.0.0 https://stylelint.io/migration-guide/to-14#function-calc-no-invalid-rule

Impossible de faire le passage a 14.x.x sans avoir `Unknown rule function-calc-no-invalid  function-calc-no-invalid` comme erreur dans chaque fichier d'un projet utilisant `@equisoft/stylelint-config-styled-components`. 

La règle existe encore dans la version 20.0.0 de `stylelint-config-standard` et est retiré dans la version 23.0.0 où toutes les dépendances à `stylelint` avant 14.0.0 sont retirées. 

La version plus récente est 25.0.0 (requiert `stylelint` 14.4.0) mais il faudrait au moins 23.0.0 pour pouvoir mettre à jour `stylelint` dans les autres projets.

**Comment by meriouma** [comment]
Fixed avec la dernière release (2.0.0). Voir la section [Installation](https://github.com/kronostechnologies/standards/tree/master/javascript/packages/stylelint-config#installation) pour la liste de packages à installer maintenant.
